// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5MV3t_ojOg7VdN9npS8P272ioyW6pq2A',
    appId: '1:694950393175:web:77c55d28cdc8abf3c67a12',
    messagingSenderId: '694950393175',
    projectId: 'flutter-fast-aid',
    authDomain: 'flutter-fast-aid.firebaseapp.com',
    storageBucket: 'flutter-fast-aid.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoo0mCEEsqqJeXefh8CzL9_l_QntsdS3U',
    appId: '1:694950393175:android:c5c6682ac4b7c4e2c67a12',
    messagingSenderId: '694950393175',
    projectId: 'flutter-fast-aid',
    storageBucket: 'flutter-fast-aid.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADEncuo9RBZbmUeP2xTU8FF3jUImjRchY',
    appId: '1:694950393175:ios:63cc8a7af81fb0cbc67a12',
    messagingSenderId: '694950393175',
    projectId: 'flutter-fast-aid',
    storageBucket: 'flutter-fast-aid.appspot.com',
    iosBundleId: 'com.mujuzimoses.portfolioAmbApp',
  );
}
